spring.datasource.url=jdbc:mysql://localhost:3306/internships
spring.datasource.username=testUser1
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# Custom config for tickets
internships.auto-publish=false
candidates.visible-by-default=false
